version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/active.conf:/etc/nginx/conf.d/upstream.conf
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'" 
    depends_on:
      - blue
      - green

  blue:
    build: ./blue
    container_name: blue
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 3s
      retries: 3

  green:
    build: ./green
    container_name: green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 3s
      retries: 3
