FROM python:3.12-slim

WORKDIR /app

COPY app.py .

RUN pip install flask
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*
EXPOSE 5000

CMD ["python", "app.py"]
